### ISSUE TITLE
error stacktrace

### ISSUE THREAD

**Issue by brxkensmile** [klesun/deep-js-completion#3]
2018-08-09 10:51:19,858 [ 357515]  ERROR - on.CompletionProgressIndicator - PhpStorm 2018.2.1 EAP  Build #PS-182.3911.19 
2018-08-09 10:51:19,858 [ 357515]  ERROR - on.CompletionProgressIndicator - JDK: 1.8.0_152-release 
2018-08-09 10:51:19,858 [ 357515]  ERROR - on.CompletionProgressIndicator - VM: OpenJDK 64-Bit Server VM 
2018-08-09 10:51:19,858 [ 357515]  ERROR - on.CompletionProgressIndicator - Vendor: JetBrains s.r.o 
2018-08-09 10:51:19,858 [ 357515]  ERROR - on.CompletionProgressIndicator - OS: Linux 
2018-08-09 10:51:19,858 [ 357515]  ERROR - on.CompletionProgressIndicator - Last Action: EditorEnter 
2018-08-09 10:51:20,283 [ 357940]   INFO - j.ide.plugins.RepositoryHelper - using cached plugin list (updated at 18.9.8 10:41) 
2018-08-09 10:51:33,467 [ 371124]  ERROR - on.CompletionProgressIndicator - null 
java.lang.NullPointerException
	at org.klesun.deep_js_completion.completion_providers.DeepKeysPvdr.addCompletions(DeepKeysPvdr.scala:93)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:141)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:89)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:149)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:142)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor$2.addCompletions(LiveTemplateCompletionContributor.java:92)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:141)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:89)
	at com.intellij.codeInsight.completion.CompletionService.performCompletion(CompletionService.java:118)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.a(CompletionProgressIndicator.java:815)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.runContributors(CompletionProgressIndicator.java:800)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.a(CodeCompletionHandlerBase.java:266)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1151)
	at com.intellij.codeInsight.completion.AsyncCompletion.tryReadOrCancel(CompletionThreading.java:181)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.a(CodeCompletionHandlerBase.java:263)
	at com.intellij.codeInsight.completion.AsyncCompletion.a(CompletionThreading.java:108)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.codeInsight.completion.AsyncCompletion.a(CompletionThreading.java:104)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:310)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by klesun** [comment]
2018.06.16.001

**Comment by klesun** [comment]
d27728f044edf0470b348cfcf9e4d04ce4e39238
