### ISSUE TITLE
new stracktrace

### ISSUE THREAD

**Issue by brxkensmile** [klesun/deep-js-completion#7]
```java
java.lang.NullPointerException
	at org.klesun.deep_js_completion.entry.PathStrGoToDecl$.$anonfun$getReferencedFile$5(PathStrGoToDecl.scala:27)
	at scala.Option.flatMap(Option.scala:171)
	at org.klesun.deep_js_completion.entry.PathStrGoToDecl$.getReferencedFile(PathStrGoToDecl.scala:26)
	at org.klesun.deep_js_completion.entry.PathStrGoToDecl.$anonfun$getGotoDeclarationTargets$3(PathStrGoToDecl.scala:44)
	at scala.Option.flatMap(Option.scala:171)
	at org.klesun.deep_js_completion.entry.PathStrGoToDecl.getGotoDeclarationTargets(PathStrGoToDecl.scala:44)
	at com.intellij.codeInsight.navigation.actions.GotoDeclarationAction.findTargetElementsNoVS(GotoDeclarationAction.java:279)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.getInfoAt(CtrlMouseHandler.java:487)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.getInfoAt(CtrlMouseHandler.java:466)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.access$1700(CtrlMouseHandler.java:89)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.doExecute(CtrlMouseHandler.java:737)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.access$2200(CtrlMouseHandler.java:668)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider$1.performInReadAction(CtrlMouseHandler.java:714)
	at com.intellij.openapi.progress.util.ReadTask.lambda$runBackgroundProcess$0(ReadTask.java:66)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:979)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:57)
	at com.intellij.openapi.progress.util.ReadTask.runBackgroundProcess(ReadTask.java:66)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runUnderProgress$4(ProgressIndicatorUtils.java:227)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$3(CoreProgressManager.java:180)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:583)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:533)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:180)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runUnderProgress(ProgressIndicatorUtils.java:225)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.access$100(ProgressIndicatorUtils.java:33)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$4.run(ProgressIndicatorUtils.java:176)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by klesun** [comment]
https://github.com/klesun/deep-js-completion/releases/tag/2018.10.25.001
